### ISSUE TITLE
Array based structure

### ISSUE THREAD

**Issue by Ohems** [jroyalty/jglm#17]
Wouldn't it be more reasonable to use an array based structure for storing vector and matrix data? This would enable implementing several generic operations like equal comparison in the abstract base classes without the speed decrease from having to rebuild the arrays every time. Sure we may lose some performance when fetching array values instead of direct variable references and looping through values without addressing them directly, but that should be within reasonable limits and the code becomes much shorter and nicer.

One major negative side would be that something like `v[0]` isn't as readable as just `x`. For this, I'd suggest shortening the getter functions to non-standard form like `x()` since it's rather reasonable to forgo some standards in this case. We could then use these getter functions instead of the array references for added verbosity. Even if the getters can't be shortened (for example to preserve API), it's still just a few characters more and we could also do stuff like `v[X]`.

I can work out a pull request for this, I just need the acceptance of the repo owner so that I won't be doing useless work since there's still quite a bit of it related.

**Comment by jroyalty** [comment]
Thanks for the suggestion, but to be honest, I'm not so keen on this.  It would be a lot of refactoring, plus the code is already pretty clean.  Granted it's verbose under the covers, but I'm okay with that since the interface is straightforward.  I'm more interested in avoiding array copies and indirection, etc.

I would be cool with adding some constructors (in places that don't have them) that take arrays.
